/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class mkdb_Storage_KeyIterator */

#ifndef _Included_mkdb_Storage_KeyIterator
#define _Included_mkdb_Storage_KeyIterator
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
